---
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancypagestyle{plain}{\pagestyle{fancy}}
- \headheight 35pt
- \fancyhead[LE,LO]{Abowath, Blakely, \\ Garrison, Loui, Peir \\}
- \fancyhead[CO,CE]{\textbf{\Large Forecasting Bikesharing Usage \\ Team 10 - Final Report} \\ https://github.gatech.edu/MGT-6203-Fall-2023-Canvas/Team-10}
- \fancyhead[RE,RO]{MGT 6203 \\ Fall 2023 \\}
- \fancyfoot[RE,RO]{\small \thepage}
- \fancyfoot[CE,CO]{}
- \headsep 1.5em
output: pdf_document
fontsize: 11pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
require(gridExtra)
library(kableExtra)
library(broom)
```
# Forecasting Bikesharing Usage for DC's Capital Bikshare System

# Table of Contents

* Introduction
* Overview of Project
* Overview of Data
* Overview of Modeling
* Conclusion
* Works Cited

# Introduction
Background information and problem framing

# Overview of Project
General approach and initial hypotheses

# Overview of Data

## Initial Data Set:

We started by just looking at two years of Capital Bikeshare usage from this dataset:
https://archive.ics.uci.edu/dataset/275/bike+sharing+dataset 

The dataset contains 2011 and 2012 historical usage data from Washington, DC’s public 
Capital Bikeshare program, one of the first large scale 
bikeshare programs in the nation. Usage data is broken out by day and by hour.
Additional data included a variety of information on weather, season, and whether
a day was a holiday:

    - holiday : whether day is holiday or not (extracted from http://dchr.dc.gov/page/holiday-schedule)
    - weekday : day of the week
    - workingday : if day is neither weekend nor holiday is 1, otherwise is 0.
    + weathersit :
   	 - 1: Clear, Few clouds, Partly cloudy, Partly cloudy
   	 - 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist
   	 - 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds
   	 - 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog
    - temp : Normalized temperature in Celsius. The values are divided to 41 (max)
    - atemp: Normalized feeling temperature in Celsius. The values are divided to 50 (max)
    - hum: Normalized humidity. The values are divided to 100 (max)
    - windspeed: Normalized wind speed. The values are divided to 67 (max)
    - casual: count of casual users
    - registered: count of registered users
    - cnt: count of total rental bikes including both casual and registered

## Data Cleaning Process

## Key Variables and Exploratory Data Analysis



## Additional Scraping, Cleaning

Initial EDA on the dataset we began with indicated we did not have sufficient
data to fit any models that could improve upon linear regression. So, we scraped
and combined two different datasets. We used python scripts located in the
Other Resources directory to do this.

* Capital Bikeshare usage data from 01-01-2013 through 12-31-2017, from
Capital Bikeshare (https://ride.capitalbikeshare.com/system-data)
* Weather data for DC for the same time period, from NOAA

The Bikeshare data only counted trips taken, and did not distinguish between
registered or casual users.

The Weather data included the day's high temperature, precipitation, and average
daily windspeed.

## Key Predictors

# Overview of Modeling
Model Types and Comparison
Model Selection and Optimization
Model Performance
Detailed evaluation and interpretation of results

#Conclusion
Overall conclusion and key learnings

# Works Cited

Bean, R., Pojani, D., & Corcoran, J. (2021). How does weather affect bikeshare use? A comparative analysis of forty cities across climate zones. _Journal of Transport Geography_, 95. https://doi.org/10.1016/j.jtrangeo.2021.103155.

Eren, E., & Uz, V. E. (2020). A review on bike-sharing: The factors affecting bike-sharing demand. _Sustainable Cities and Society_, 54. https://doi.org/10.1016/j.scs.2019.101882

Ashgar, H. I., Elhenawy, M., & Rakha, H. A. (2019). Modeling bike counts in a bike-sharing system considering the effect of weather conditions. _Case Studies on Transport Policy_, 7(2), 261-268. https://doi.org/10.1016/j.cstp.2019.02.011
